version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: brunoformiga
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
